// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBqtZu_BVEs3kZ6JqXzSzfyM7vpFHSpzk',
    appId: '1:69412235022:web:1556f3cca006a7b285195f',
    messagingSenderId: '69412235022',
    projectId: 'login-c8219',
    authDomain: 'login-c8219.firebaseapp.com',
    storageBucket: 'login-c8219.appspot.com',
    measurementId: 'G-3F51WYVBEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu--SIgET-qm-hlZMFNGYK3nXuJW6RRoo',
    appId: '1:69412235022:android:81e8672e426c376185195f',
    messagingSenderId: '69412235022',
    projectId: 'login-c8219',
    storageBucket: 'login-c8219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq9g0-EZRQgWVVbL1Dn4i8C8HdBuQpvfM',
    appId: '1:69412235022:ios:d123fff6bde8498485195f',
    messagingSenderId: '69412235022',
    projectId: 'login-c8219',
    storageBucket: 'login-c8219.appspot.com',
    iosClientId: '69412235022-c7ehganj1ophf7jm6k9r4qegvnjs0g5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq9g0-EZRQgWVVbL1Dn4i8C8HdBuQpvfM',
    appId: '1:69412235022:ios:d123fff6bde8498485195f',
    messagingSenderId: '69412235022',
    projectId: 'login-c8219',
    storageBucket: 'login-c8219.appspot.com',
    iosClientId: '69412235022-c7ehganj1ophf7jm6k9r4qegvnjs0g5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ui',
  );
}
